### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by Otto-AA** [Veneris-Group/TOD-Location-Rectification#1]
Hi, I am thinking about using this project in the course of my master thesis (validating it against some datasets, fine-tuning it, and if it works sufficiently well then also submitting it back to the slither repository).

Would it be possible to add a LICENSE to this repository, so it is clear whether this usage is ok?

You can do so here: https://github.com/Veneris-Group/TOD-Location-Rectification/community/license/new?branch=main&filename=LICENSE&template=mit

**Comment by beillahi** [comment]
Hello, thanks for reaching out. I added the following [License](https://github.com/Veneris-Group/TOD-Location-Rectification/blob/main/README.md#license) description of the files in the repository. I hope this helps.
